# fly.toml app configuration file generated for talking-heads on 2023-11-07T05:42:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "talking-heads"
primary_region = "bos"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "3s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"
